Working json loading of creds
if the creds are saved correctly we think this will work. Currently
  there is something up with the creds in the db - they are not being
  decrypted when loaded. We have not investigated this yet. It could be
  that replacing this with the contents of the creds file is preventing
  them from being encrypted and actually we need to deliveratly decrypt
  the creds when loading them. It could also be that the key to decrypt
  is environment specific and so copied down dbs will always look wrong.

  Having investigated this it seems that the latter is true - preview or
  development cannot decrypt production credentials.

  Once the creds are in the right format we get this error for GA:

  InvalidClientSecretsError: File not found:
  "/data/apps/performanceplatform

  Because we do not yet support non file based creds in the pp
  collector. We need to support passing the whole files in rather than
  just paths to files.